-- 코드를 입력하세요
SELECT uu.USER_ID
      ,uu.NICKNAME
      ,SUM(ub.price) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS ub
LEFT JOIN USED_GOODS_USER AS uu ON ub.WRITER_ID = uu.USER_ID
WHERE STATUS = 'DONE'
GROUP BY USER_ID
HAVING total_sales >= 700000
ORDER BY TOTAL_SALES