SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
WHERE  C.CAR_TYPE = '세단' AND    -- 자동차 종류 세단
       MONTH(H.START_DATE) = 10  -- 10월에 대여를 시작한    
ORDER BY 1 DESC      